GET http://localhost:3001/blogs

###

GET http://localhost:3001/blogs/60c8eddb2750d5628ce4d6a7

###

POST http://localhost:3001/blogs
Content-Type: application/json

{
    "title": "A day in the life of",
    "author": "Huy Tran",
    "url": "www.huytran.com",
    "lkes": 5
}