POST http://localhost:3002/api/patients
Content-Type: application/json

{
    "name": "James Hetfield",
    "dateOfBirth": "1990-02-03",
    "ssn": "fdsfsd",
    "gender": "male",
    "occupation": ""
}

###

GET http://localhost:3002/api/patients/d2773598-f723-11e9-8f0b-362b9e155667